// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// as5600 //
// ------ //

#define as5600_wrap_target 2
#define as5600_wrap 29
#define as5600_pio_version 0

static const uint16_t as5600_program_instructions[] = {
    0x80a0, //  0: pull   block
    0xa047, //  1: mov    y, osr
            //     .wrap_target
    0xa7e2, //  2: mov    osr, y                 [7]
    0xe080, //  3: set    pindirs, 0
    0xf126, //  4: set    x, 6            side 0 [1]
    0x7081, //  5: out    pindirs, 1      side 0
    0xb942, //  6: nop                    side 1 [1]
    0x1045, //  7: jmp    x--, 5          side 0
    0xf081, //  8: set    pindirs, 1      side 0
    0xb942, //  9: nop                    side 1 [1]
    0xb042, // 10: nop                    side 0
    0xb042, // 11: nop                    side 0
    0xb942, // 12: nop                    side 1 [1]
    0xf027, // 13: set    x, 7            side 0
    0xb042, // 14: nop                    side 0
    0xb842, // 15: nop                    side 1
    0x4001, // 16: in     pins, 1
    0x104e, // 17: jmp    x--, 14         side 0
    0xe080, // 18: set    pindirs, 0
    0xf927, // 19: set    x, 7            side 1 [1]
    0xf081, // 20: set    pindirs, 1      side 0
    0xb042, // 21: nop                    side 0
    0xb842, // 22: nop                    side 1
    0x4001, // 23: in     pins, 1
    0x1055, // 24: jmp    x--, 21         side 0
    0xe081, // 25: set    pindirs, 1
    0xb942, // 26: nop                    side 1 [1]
    0xf180, // 27: set    pindirs, 0      side 0 [1]
    0xba42, // 28: nop                    side 1 [2]
    0xe781, // 29: set    pindirs, 1             [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program as5600_program = {
    .instructions = as5600_program_instructions,
    .length = 30,
    .origin = -1,
    .pio_version = as5600_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config as5600_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + as5600_wrap_target, offset + as5600_wrap);
    sm_config_set_sideset(&c, 2, true, true);
    return c;
}
#endif

