// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---- //
// spwm //
// ---- //

#define spwm_wrap_target 0
#define spwm_wrap 13
#define spwm_pio_version 0

static const uint16_t spwm_program_instructions[] = {
            //     .wrap_target
    0x9880, //  0: pull   noblock         side 2
    0x7030, //  1: out    x, 16           side 0
    0xa0c1, //  2: mov    isr, x
    0x0043, //  3: jmp    x--, 3
    0x6030, //  4: out    x, 16
    0xb441, //  5: mov    y, x            side 1
    0x0046, //  6: jmp    x--, 6
    0xa042, //  7: nop
    0xc000, //  8: irq    nowait 0
    0x0089, //  9: jmp    y--, 9
    0xa042, // 10: nop
    0xb026, // 11: mov    x, isr          side 0
    0x004c, // 12: jmp    x--, 12
    0xa242, // 13: nop                           [2]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program spwm_program = {
    .instructions = spwm_program_instructions,
    .length = 14,
    .origin = -1,
    .pio_version = spwm_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config spwm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + spwm_wrap_target, offset + spwm_wrap);
    sm_config_set_sideset(&c, 3, true, false);
    return c;
}
#endif

